[cmd_duration]
disabled = true

[character]
symbol = ">"
style_success = "white"
style_failure = "dim red"

[git_branch]
style = "white"

[git_status]
disabled = "false"

[aws]
symbol = "aws:"
displayed_items = "profile"
