InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes

Diagnostics:
  UnusedIncludes: Strict

---
If:
  PathMatch:
    [
      /home/mharman/work/zephyr-tracker/.*,
      /home/mharman/work/zephyr-tracker-root/.*,
      /opt/ncs/.*,
      /home/mharman/work/esp-idf/.*,
      /home/mharman/work/esp-wifi-scan/.*,
      /home/mharman/raven/.*,
      /opt/esp/.*,
    ]

CompileFlags:
  Remove:
    - "-f*"
    - "-m*"
