InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes

Diagnostics:
  UnusedIncludes: Strict

---
If:
  PathMatch: /home/mharman/work/zephyr-tracker/.*

CompileFlags:
  Remove:
    - "-f*"
    - "-m*"
