format = """
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmake\
$elixir\
$golang\
$python\
$rust\
$zig\
$line_break\
$status\
$character\
"""

[aws]
disabled = true
symbol = "aws:"
displayed_items = "profile"

[cmake]
disabled = true

[cmd_duration]
disabled = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"

[elixir]
format = "[$symbol$version]($style)"

[golang]
format = "[$symbol$version]($style)"

[package]
disabled = true

[python]
format = "[$symbol$version]($style)"

[rust]
format = "[$symbol$version]($style) "

[zig]
format = "[$symbol$version]($style) "
