format = """
$custom\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmake\
$elixir\
$golang\
$python\
$rust\
$zig\
$line_break\
$status\
$character\
"""

[aws]
disabled = true
symbol = "aws:"
displayed_items = "profile"

[cmake]
disabled = true

[cmd_duration]
disabled = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"

[custom.podman-container]
command = "grep '^name=' /run/.containerenv | cut -d'=' -f2- | tr -d '\"'"
when = "[ -e /run/.containerenv ]"

## TODO
#[custom.docker-container]
#command = "????"
#when = "[ -e /run/.dockerenv ]"

[package]
disabled = true
