#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Mathew Harman"
email = "mathew.harman@gmail.com"

[aliases]
dt = ["diffedit", "--tool=nvimdifftool"]

[fix.tools.clang-format]
command = ["clang-format", "--assume-filename=$path"]
patterns = ["glob:**/*.c", "glob:**/*.cpp", "glob:**/*.h", "glob:**/*.hpp"]

[ui]
editor = "nvim"
diff-editor = "hunknvim"
diff-instructions = false

[merge-tools.jj-stage]
program = "nvim"
diff-args = [
  "-c",
  "let g:flatten_wait=1",
  "-c",
  "let g:autoformat=v:false",
  "-c",
  "JJDiffStage $left $right",
]
edit-args = [
  "-c",
  "let g:flatten_wait=1",
  "-c",
  "let g:autoformat=v:false",
  "-c",
  "JJDiffStage $left $right",
]

[merge-tools.nvimdifftool]
program = "nvim"
diff-args = [
  "-c",
  "let g:flatten_wait=1",
  "-c",
  "let g:autoformat=v:false",
  "-c",
  "packadd nvim.difftool",
  "-c",
  "DiffTool $left $right",
]
edit-args = [
  "-c",
  "let g:flatten_wait=1",
  "-c",
  "let g:autoformat=v:false",
  "-c",
  "packadd nvim.difftool",
  "-c",
  "DiffTool $left $right",
]

[merge-tools.hunknvim]
program = "nvim"
diff-args = [
  "-c",
  "let g:flatten_wait=1",
  "-c",
  "let g:autoformat=v:false",
  "-c",
  "packadd nvim.difftool",
  "-c",
  "DiffEditor $left $right $output",
]
edit-args = [
  "-c",
  "let g:flatten_wait=1",
  "-c",
  "let g:autoformat=v:false",
  "-c",
  "packadd nvim.difftool",
  "-c",
  "DiffEditor $left $right $output",
]

[signing]
behavior = "own"
backend = "gpg"
key = "D5A9E07E5740AA47"
